; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:starboy]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_8MB.csv
monitor_speed = 115200
monitor_port = /dev/ttyACM0
monitor_filters = direct
upload_speed = 921600
build_flags = 
	-I ${PROJECT_INCLUDE_DIR}
	-DBOARD_HAS_PSRAM
	-DARDUINO_ESP32S3_DEV
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=3
	-DLCD_RESET=8
	-DLCD_TE=9
	-DLCD_CS=10
	-DLCD_SCL=11
	-DLCD_D0=12 -DLCD_D1=13 -DLCD_D2=14 -DLCD_D3=15
	-DTOUCH_INT=6
	-DTOUCH_RST=7
	-DI2C_SDA=47
	-DI2C_SCL=48
	-DI2S_ASDOUT=40
	-DI2S_LRCK=41
	-DI2S_DSDIN=42
	-DI2S_MCLK=38
	-DI2S_SCLK=39
	-DPA_CTRL=46
	-DBTN_PWR=17
	-DBTN_BOOT=0
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_DRAW_SW_ASM=LV_DRAW_SW_ASM_NONE
    -DLV_USE_DRAW_ESPRESSIF_PPA=0  ; если не используете PPA
    -DLV_USE_ANIMIMG=0             ; чтобы убрать warning
	-I ${PROJECT_LIBDEPS_DIR}/lvgl/lvgl
    -DLV_LVGL_H_INCLUDE_SIMPLE=1
lib_deps = 
	moononournation/GFX Library for Arduino@^1.6.5
	lvgl/lvgl@^9.5.0
; 👇 Исключаем ARM-специфичные ассемблерные файлы
build_src_filter = 
    +<*>
    -<draw/sw/blend/helium/>
    -<draw/sw/blend/neon/>
    -<draw/convert/helium/>
    -<draw/convert/neon/>
    -<draw/sw/arm2d/>

